from setuptools import setup

setup(
    name='aionhl',
    version='0.0.1',
    author='Brayden Carlson',
    author_email='braycarlson@hotmail.com',
    description='An asynchronous wrapper around the unofficial NHL API',
    long_description_content_type='text/x-rst',
    url='https://github.com/braycarlson/aionhl',
    packages=['aionhl'],
    license='MIT',
    install_requires=['aiohttp[speedups]'],
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Framework :: AsyncIO',
        'Intended Audience :: Developers',
        'Natural Language :: English',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3 :: Only',
        'Topic :: Internet',
        'Topic :: Software Development :: Libraries',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Topic :: Utilities',
    ],
)
